services:
  embedded:
    build:
      context: ./embedded
      dockerfile: Dockerfile
      args:
        FINAL_IMAGE: "scratch"
    container_name: asm-embedded
    ports:
      - "8080:8080"
    restart: unless-stopped

  external:
    build:
      context: ./external
      dockerfile: Dockerfile
      args:
        FINAL_IMAGE: "scratch"
    container_name: asm-external
    ports:
      - "8081:8080"
    restart: unless-stopped

  file:
    build:
      context: ./file
      dockerfile: Dockerfile
      args:
        FINAL_IMAGE: "scratch"
    container_name: asm-file
    ports:
      - "8082:8080"
    restart: unless-stopped
